### PR TITLE
Quiz creator bug fixes

### PR DESCRIPTION
**Pull request by ZeroConfidence**
# Description
//bug fixes for the pop-up on the quizCreator page

## What is added/changed/removed
removed css which fixed the pop-up to the center of the window 
added checks to see if a pop-up already existed before creating a new one

## Issue/fixes reference
fixed issues with the question creator/editor pop-up partially hiding behind the moodle course wing
fixed issues where multiple pop-ups could be created by clicking the add question or edit question buttons

## Testing

# Checks
- [ ] Updated / added tests for these changes
- [ ] PHPunit locally passed
- [ ] Codesniffer locally passed
- [ ] Behat locally passed

### CODE REVIEW

**Comment by Peterrahr** [comment]
It is still possible while the popup menu is open to delete a question + the "take live quiz" link is still active

**Comment by ZeroConfidence** [comment]
> It is still possible while the popup menu is open to delete a question + the "take live quiz" link is still active. It corrupts the DB, when edit menu is open, I delete question while it is open, and I press take live quiz while menu is open

will start working on making those issues then. they'll be in a future PR

**Comment by Peterrahr** [comment]
@ZeroConfidence it is apparently a current issue when you delete a question and nothing with the popup menu and your PR. We are looking into atm

**Review by mantarias — APPROVED** [review]

**Comment by Peterrahr** [comment]
> @ZeroConfidence it is apparently a current issue when you delete a question and nothing with the popup menu and your PR. We are looking into atm

The deletion is fixed in #173

**Comment by ZeroConfidence** [comment]
so.. there was no problem with the phpunit or behat tests before the merging staging into the PR branch... and all the changes (excluding the two lines from the css file was in files untouched be this pr... seems like staging isn't passing the tests...

**Review by adomasciplys — COMMENTED** [review]
image

The phpunit test pass fine in staging. But I think something is wrong with the CI-pipeline at the moment. It does not seem like it gets to running the tests, neither for phpunit or Behat. @DeeKahy, can you take a look at this

**Comment by Andreas272** [comment]
I tested the changes manually, and it works. I have no comments to the code except that we should remove the changes to package.json and npm-shrinkwrap.json if possible (as we discussed).

**Comment by od45pv** [comment]
closes #170

**Pull request merged**
