### PR TITLE
add - The Docker Setup

### PR DESCRIPTION
**Pull request by Thekid2002**
Added files to enable setting up a dockerised Moodle instance. Also moved livequiz to be in main directory to not screw up the files being moved.

### CODE REVIEW

**Comment by Thekid2002** [comment]
THIS PR IS NOT TO BE CLOSED - Before further discussion d. 17/10/2024. If it is closed none the less, this will be seen as an act of war.

**Comment by DeeKahy** [comment]
Could've just reopened the old PR after you answered my question and made the changes I requested day one.

My previous question stands.

It looks like it is the same as the `Præsentation af et containerized setup` that is described below. Is that correct? @Thekid2002 

```
Præsentation af et containerized setup
Repository’et kan godt hurtigt komme til at fylde meget, blive rodet og i det hele taget være svært at finde hoved og hale i. Derfor foreslår vi at der bliver lavet et nyt repository udelukkende til pluginet og altså ikke også Moodle koden. Dette er muligt, da den nyligt containerized version af Moodle kan overtage pladsen fra Moodle. Denne løsning medbringer flere fordele, blandt andet kræver det mindre installation, virker på flere system arkitekturer og tager kortere tid for alle at sætte op.
```

**Comment by vjohns22** [comment]
> Could've just reopened the old PR after you answered my question and made the changes I requested day one.
> 
> My previous question stands.
> 
> It looks like it is the same as the `Præsentation af et containerized setup` that is described below. Is that correct? @Thekid2002
> 
> ```
> Præsentation af et containerized setup
> Repository’et kan godt hurtigt komme til at fylde meget, blive rodet og i det hele taget være svært at finde hoved og hale i. Derfor foreslår vi at der bliver lavet et nyt repository udelukkende til pluginet og altså ikke også Moodle koden. Dette er muligt, da den nyligt containerized version af Moodle kan overtage pladsen fra Moodle. Denne løsning medbringer flere fordele, blandt andet kræver det mindre installation, virker på flere system arkitekturer og tager kortere tid for alle at sætte op.
> ```

correct
image

**Comment by DeeKahy** [comment]
This was denied, not because of the database, but because of the way it changes the entire repository structure. Your PO knows this.

Is there any new information, or anything that wasn't originally covered by your PO the first time?

**Comment by Thekid2002** [comment]
> This was denied, not because of the database, but because of the way it changes the entire repository structure. Your PO knows this.
> 
> 
> 
> Is there any new information, or anything that wasn't originally covered by your PO the first time?

Jeg anker sagen, vi ses til næste PO møde 😀 Ha en rigtigt god dag

**Comment by ZeroConfidence** [comment]
> THIS PR IS NOT TO BE CLOSED - Before further discussion d. 17/10/2024. If it is closed none the less, this will be seen as an act of war.

act of war? tempting

**Pull request closed without merging**
