### PR TITLE
update - Updated install.xml (Database setup)

### PR DESCRIPTION
**Pull request by vjohns22**
Updated the install.xml file in accordance with the ER-diagram (https://drive.google.com/file/d/1TSJK4q8L0okpjn74jqJlCwS9RFhyrtO8/view?usp=sharing).

### CODE REVIEW

**Comment by DeeKahy** [comment]
Does this have some sort of cohesion with the moodle question bank?

**Comment by vjohns22** [comment]
> Does this have some sort of cohesion with the moodle question bank?
> 
> I remember having a discussion about it but don't know if it ever turned into anything.

To me, this sounds like a matter of implementation.
If we want the plugin to have access to the existing Moodle question bank, we can handle it through querying that table. Similarly, to reuse past LiveQuiz questions, the page for creating a LiveQuiz could allow the user to query the Questions table that we create specifically for the LiveQuiz.

**Comment by CarlHejlesen** [comment]
image
I have converted the xml to postgress structure. To try to visual represent what they have made

**Review by ZeroConfidence — APPROVED** [review]
looks well good and well structured.

**Review by DeeKahy — APPROVED** [review]
Looks fine.

**Pull request merged**
