### PR TITLE
Update - PHPUnit and nix-shell

### PR DESCRIPTION
**Pull request by mantarias**
- sped up phpunit
- implemented fixes used here into nix shell https://deekahy.github.io/UniNotes/5.%20Semester/

### CODE REVIEW

**Review by ZeroConfidence — DISMISSED** [review]
i don't see any issues

**Review by ChristofferGamel — DISMISSED** [review]

**Review by adomasciplys — APPROVED** [review]
Works on my Mac with a fresh database. Tried all the commands and they work.

**Comment by mantarias** [comment]
Mac should now be fixed, please follow the guide https://deekahy.github.io/UniNotes/5.%20Semester/ to verify

**Review by EmilChri — DISMISSED** [review]

**Comment by mantarias** [comment]
Added behat to nix-shell should only work on WSL and Linux no mac support.
Mac support will prob need to rely on #67 
the new command can be run with beit

**Comment by ChristofferGamel** [comment]
image
Supposed to look like that?

**Comment by mantarias** [comment]
> image Supposed to look like that?

Can you retry it?

**Comment by ChristofferGamel** [comment]
> > image Supposed to look like that?
> 
> Can you retry it?

Retry:

image

**Review by ChristofferGamel — DISMISSED** [review]
image
👏

**Comment by mantarias** [comment]
Seems like sometimes GitHub fails to clone moodle-browser-config deleting /server/moodle/moodle-browser-config and rerunning command should fix it

**Comment by mantarias** [comment]
> Seems like sometimes GitHub fails to clone moodle-browser-config. Deleting /server/moodle/moodle-browser-config and rerunning command should fix it

should be fixed now made it go into the folder and git stash the changes which should bring back its content

**Review by DeeKahy — APPROVED** [review]
image

behat works on NixOS :)

**Review by ChristofferGamel — APPROVED** [review]

**Comment by DeeKahy** [comment]
@ZeroConfidence @EmilChri @od45pv

**Review by od45pv — APPROVED** [review]

**Review by ZeroConfidence — APPROVED** [review]

**Review by EmilChri — APPROVED** [review]

**Pull request merged**
