### PR TITLE
fix - all temprary and cache files should now no longer be tracked by git

### PR DESCRIPTION
**Pull request by DeeKahy**
This pull request is regarding the PO meeting about the git tracking files it shouldn't track. This is hopefully the test for it but requires a LOT of testing before we commit it anywhere.

Luckily, if I blocked too much, the fix is very simple.

### CODE REVIEW

**Comment by ChristofferGamel** [comment]
Make it as a draft PR instead ;)

**Comment by DeeKahy** [comment]
@EmilChri @ChristofferGamel @AlliasGhorbani @mantarias 

Please check if this breaks anything on your systems.

**Review by EmilChri — APPROVED** [review]

**Review by mantarias — APPROVED** [review]
Everything seems to work both in WSL and windows

**Comment by AlliasGhorbani** [comment]
My Note:

When pulling there are no logs, which breaks it when starting moodle. I put my own logs in from seperate fork. it works, but database is non-functional.

I am having issues with the database:
- "cant find mysql\data\mysql.pid." AND "mysql\bin\mysql.exe"
(maybe can have somthing to do with it being in "xampp\mysql\data\mysql.pid."

Might be some just be some issues on my end. Do let me know

**Comment by mantarias** [comment]
Added the log folder, which should allow Windows users to run the project with either "Start Moodle" or "apache_start.bat".
It will still complain about MySQL but should continue anyway after a few seconds. You needed to be running "MariaDB" service in the background as a service (only applicable if you disabled it)
Seems having folder named something else than "Moodle-1" might cause merge conflicts later as start moodle modifies some config files
@DeeKahy @ChristofferGamel @AlliasGhorbani @EmilChri

**Comment by Lazcse** [comment]
It works for me on windows as well

**Comment by Theis194** [comment]
Works for me 👍

**Comment by DeeKahy** [comment]
works on macos (as well as macos works right now)

will test linux tonight

**Comment by AlliasGhorbani** [comment]
seems to be running fine


Moodle does put out errors.
Startup errors:
Error while calling mysql\bin\mysqld.exe...

Shutdown errors:
Can't find apache\logs\httpd.pid. (one time error)
Can't find mysql\data\mysql.pid.

NOTE:
mysql folder is missing when reinstating pr/4.

**Pull request merged**
